### ISSUE TITLE
Sketch File

### ISSUE THREAD

**Issue by LeCoupa** [konpa/devicon#113]
Thank you for this fantastic package! I don't know if it could be interested to your community but I have just built a sketch library to easily import these icons in my artboards.

See the attached file in the link below.

https://dribbble.com/shots/4476739-Background-with-Technology-Icons

**Comment by iamclaytonray** [comment]
Hey @LeCoupa! This is definitely interesting. I personally don't use anything other than Sketch but I'm not sure about the greater community. What are you envisioning with this request? I assume the Sketch file would be locked into git and we'd use Sketch to manage icons? Thanks!

**Comment by fearrr** [comment]
@LeCoupa TY man, this is really saved my time!
