### ISSUE TITLE
Add to npm registry?

### ISSUE THREAD

**Issue by vizv** [konpa/devicon#12]
Could you make this awesome project available on the npm registry so I can add into dependencies of my `package.json`?

I saw there is already a `package.json` in the project root directory, however it's not available on the npm registry.

**Comment by konpa** [comment]
Sure. I'll do this as soon as possible.

**Comment by vizv** [comment]
Thanks! :+1:

**Comment by konpa** [comment]
https://www.npmjs.com/package/devicon
