### ISSUE TITLE
Update Npm Package

### ISSUE THREAD

**Issue by fausthor97** [konpa/devicon#137]
Could you please update devicon npm package to version 2.2?

**Comment by iamclaytonray** [comment]
If you could, please file your issue (and any new issues) to the new repo/fork [here](https://github.com/iamclaytonray/devicon). Thanks!

**Comment by CaitlinWeb** [comment]
Bump, this still hasn't been done! 😞

**Comment by konpa** [comment]
Done :)

https://www.npmjs.com/package/devicon
