### ISSUE TITLE
New ideas

### ISSUE THREAD

**Issue by MrSheldon** [konpa/devicon#142]
Add visual studio code and notepad++ 😂👌🏻

**Comment by Berkmann18** [comment]
-> #11

**Comment by iamclaytonray** [comment]
If you could, please file your issue (and any new issues) to the new repo/fork [here](https://github.com/iamclaytonray/devicon). Thanks!

**Comment by iamclaytonray** [comment]
Please file individual issues and pull requests. Feel free to update your OP with one icon, update the title accordingly, and then file a new issue for any other icon requests that you have that are not already filed. Thanks!

**Comment by amacado** [comment]
As @iamclaytonray mentioned, please fill a new issue for each icon and name it properly :) Thanks! :) You can reopen this when you changed it accordingly :)
