### ISSUE TITLE
MAINTAINING => New Repo!!!

### ISSUE THREAD

**Issue by iamclaytonray** [konpa/devicon#146]
Hello all. It seems the original maintainer of this repo is not actively looking to continue maintaining it. For anyone that has a PR or issue, please file them at my [fork](https://github.com/iamclaytonray/devicon). I will be actively maintaining this moving forward so if you'd like PRs to get through, that'll be the place to do it!

If you're interested in becoming a collab, let me know! Even though this library isn't a huge opportunity for getting security threats through, because of the latest `event-stream` issue, I am going to be very careful before I allow someone to have a collab status! Just bear that in mind so that we can make OSS more secure and happier!

**Comment by konpa** [comment]
@iamclaytonray Indeed, I currently have no time to maintain this repo. And it's a shame to see all these issues and PRs without answer... However, if you're willing to help I could add you as a collaborator to this repo.

Let me know if you're interested. I think it would be better than maintaining a fork.

**Comment by iamclaytonray** [comment]
Yeah, for sure! I would've reached out to you but didn't know if you'd respond so figured I'd maintain a fork. More than happy to become a collab 😄

**Comment by konpa** [comment]
Done. Thanks for your help. Don't hesitate to reach me by email if you need details, I'll try to get back to you as soon as I can.

**Comment by Berkmann18** [comment]
I can also help (if needed) although I'm admittedly not very talented in design (but can and want to improve).

**Comment by iamclaytonray** [comment]
Hey @Berkmann18! Thanks! I'll be honest, I'm not much of a designer but I didn't want to see this project die. I was going to, at the very least, maintain the repo so releases could get out of the door. I think there is a big enough community to where we can all play our part! For now, I'm just getting acquainted to everything and have to finish up some work for today and prepare for my last contract of the year. It's also the holiday season so we probably won't get _too_ many PRs merged in but starting after the new year, we're definitely going to push full-steam ahead! I'm going to make an announcement in the issue tracker for a game plan for 2019! Thanks so much!

**Comment by Berkmann18** [comment]
@iamclaytonray Thanks for your honesty and as you said we (GHers) can all play our part in improving this repo (which I would also not want to see dying) and even if the number of issues closed and PR merged is low from now to next year, it will still be a push forward.
