### ISSUE TITLE
Feature Request: Add 'Click To Copy' Buttons On Website

### ISSUE THREAD

**Issue by iamclaytonray** [konpa/devicon#150]
To help with DX, I'd like to add a "Click To Copy" button where applicable. I'd also like to add another field of just the class name itself. IE: `devicon-webpack-plain`. This way, if you already have a class stubbed out, you don't have to copy in your editor, remove the `<i class="` and `">`. You can just click the button and paste right into your code!

**Comment by Berkmann18** [comment]
That's a good idea, although naming the button "copy" near the field that contains either the SVG code or the class name, would be better.

**Comment by iamclaytonray** [comment]
Yeah, maybe we could do something like:

[https://angular.io/tutorial/toh-pt1](https://angular.io/tutorial/toh-pt1)

**Comment by Berkmann18** [comment]
Yeah, that's also good.
