### ISSUE TITLE
Feature Request: Add Sorting To Website

### ISSUE THREAD

**Issue by iamclaytonray** [konpa/devicon#151]
I think we can break it up into the following categories:

- [ ] All
- [ ] Language (Ruby, JavaScript, etc)
- [ ] Design (Photoshop, Sketch, etc)
- [ ] Framework/Library (React, Angular, etc)
- [ ] Tooling (Webpack, Parcel, etc)
- [ ] Database (Postgres, MySQL, etc)

What am I missing? (This is not high priority)

**Comment by Berkmann18** [comment]
There's also Platforms/OS/distributions (GNU/Linux, Windows, OSX, Android, etc).
There's probably more but other categories could be added later on.

**Comment by iamclaytonray** [comment]
Yeah. Thinking about it, this can become a large rabbit hole. Not sure if it's worth the time...

**Comment by Berkmann18** [comment]
@iamclaytonray Well, for the other categories (if any more non-classifiable icons were to be added), they could just go in an "other"/"miscellaneous" category (perhaps until there are enough icons to create another category).

**Comment by bartclaeys** [comment]
The challenge with the suggested categories is that it implies icon sets are fairly complete for each category. Take the design category as an example. The only icon I could find was one for Photoshop, but other mayor programs like InDesign, Sketch,... are missing.

**Comment by Berkmann18** [comment]
@bartclaeys True, however some have been requested so if we were to add all them ones that were requested then it will fill up a good chunk of all categories.
