### ISSUE TITLE
Icon request: Rust

### ISSUE THREAD

**Issue by RReverser** [konpa/devicon#161]
> Could you please add Rust (the programming language)?
Thanks!

> Either is great:
![](http://rustacean.net/assets/rustacean-orig-noshadow.svg)
![](https://upload.wikimedia.org/wikipedia/commons/d/d5/Rust_programming_language_black_logo.svg)

_Originally posted by @Gowee in https://github.com/konpa/devicon/issues/11#issuecomment-426556387_

**Comment by RReverser** [comment]
(reposted here because original issue is closed with a request to create dedicated issues for outstanding requests instead)

**Comment by iamclaytonray** [comment]
I'd certainly love to see this added. I'm swamped with work right now so I can't personally do it. I will tag this for help from the community if you are unable to!

**Comment by TimonPost** [comment]
https://github.com/rust-lang/rust/issues/11562
