### ISSUE TITLE
[ICON REQUEST]: <Matplotlib>

### ISSUE THREAD

**Issue by danaikorre** [konpa/devicon#1678]
### I have searched through the issues and didn't find my problem.

- [X] Confirm

### About the icon

Matplotlib: Visualization with Python

### Links and sources

https://matplotlib.org/

Matplotlib is a comprehensive library for creating static, animated, and interactive visualizations in Python. Matplotlib makes easy things easy and hard things possible.

**Comment by canaleal** [comment]
Hey @danaikorre Matplotlib is already in develop.
https://github.com/devicons/devicon/tree/develop/icons/matplotlib

Pull Request:
https://github.com/devicons/devicon/pull/1323
