### ISSUE TITLE
When will a new release be published?

### ISSUE THREAD

**Issue by CodeShakingSheep** [konpa/devicon#1900]
### I have searched through the issues and didn't find my problem.

- [X] Confirm

### What would you like to share?

Hi there,
I was just surprised that develop branch is 276 commits ahead of master and the last release. A lot of new icons were merged into develop since the last release. So, I was just wondering why there wasn't a release published for 1.5 years. Would be great to have a new release published soon. Thank you for this awesome project!

**Comment by weh** [comment]
This also leads to icon requests that are already done e.g. #1894, #1893, #1892, #1867, #1858,...

**Comment by canaleal** [comment]
This ticket is being closed because a new release has been made since it was created. You can view the latest release here: https://github.com/devicons/devicon/releases/tag/v2.16.0
