### ISSUE TITLE
better organization for names of icons

### ISSUE THREAD

**Issue by py563** [konpa/devicon#207]
can we club plain and original to same category and simply name it as devicon-<brand>.
other files for icon stay with same names

**Comment by amacado** [comment]
@py563 hey :) I'm not sure if i understood you right.. Can you please make some examples to clear things up? :)

**Comment by py563** [comment]
it is hard to remember which icon is plain and which is original? why are they different versions. like for java icon i think you have plain but not original. 

does original mean you got it form the brand's website?

**Comment by amacado** [comment]
As it is written in our [CONTRIBUTING.md](https://github.com/konpa/devicon/blame/master/CONTRIBUTING.md#L21-L23):

> The plain and line versions (with or without wordmark) are designed to be available in the final icon font. So they need to stay as simple as possible (one color and ensure that the paths are united before to export to svg). You can use a service like [compressor](https://compressor.io/) or [SVG Editor](https://petercollingridge.appspot.com/svg-editor) in order to optimize the svg file.
The original versions are only available in svg format, so they do not need to be as simple and they can contain numerous colors.
Some icons are really simple (like the apple one), so the original version can be used for the icon font. In this case, I'll add an alias so they can be found with the "original" or "plain" naming convention.

It is indeed possible, that there are some icons which does not implement all variations. Feel free to add them and open a pull request :)

Hope this answers your question why there are different versions and what the mean.
