### ISSUE TITLE
Maintainer - bring this project back to life 🚀

### ISSUE THREAD

**Issue by amacado** [konpa/devicon#215]
Hello, I feel sad that it seems like this project isn't actively maintained anymore. There are a lot of open pull requests which would add some very nice and useful icons. I would volunteer to collaborate on this project and try to keep it alive. I will probably not having the time to add icons by myself, but I can try to clean things up and reviewing the open pull requests/issues. @konpa if you are willing to add me I will see what's possible.

**Comment by amacado** [comment]
Thank you for adding me. I will start by organizing/labeling the pulls and issues, continuing to review some of the pull requests.

**Comment by debdutgoswami** [comment]
You should look into some of the icon PRs. Many open PRs have some very useful icons. You should consider merging them :)

**Comment by amacado** [comment]
@debdutgoswami y, planning to do that in the next days.. :)
