### ISSUE TITLE
please add these icons

### ISSUE THREAD

**Issue by foxmedia95** [konpa/devicon#25]
please add these icons

**Opera Mini
Maxthon 
Netscape
Mac
Mybb**

**Comment by darianno** [comment]
Please add SilverStripe icon (www.silverstripe.org)

**Comment by mrsdohpaz** [comment]
Would also like to see:
Blender3d, 
Unity3d, 
Threejs, 
Autodesk programs

Thanks!

**Comment by 4ndv** [comment]
Elixir and Sublime Text plz :)

**Comment by remyo** [comment]
Maybe Markdown too?

**Comment by kwstasna** [comment]
there are no plans for update soon right?

**Comment by konpa** [comment]
@kwstasna I'd like to update this repo (pull requests & icons to add) but I really have no time... I'm looking for someone to help me on maintaining this repo but without luck for now...

**Comment by kwstasna** [comment]
I understand and already your work is really appreciated! Would love to help but i dont have any idea of SVG etc. You could kindly ask at the ReadMe though! @konpa :+1:

**Comment by dmetzler1988** [comment]
Windows batch / shell scripting and PowerShell pls :)

**Comment by oligibson** [comment]
I've added all the suggested icons to #11 so we can collate them in the same place. I'm going to close this issue and if anyone wants to add more icon suggestions please comment on #11. 

For those looking to contribute to this repo you can see the [contributing.md](https://github.com/konpa/devicon/blob/master/CONTRIBUTING.md), you can open a pull request with just the icon files and I can create fonts when merging.
