### ISSUE TITLE
Ceylon?

### ISSUE THREAD

**Issue by Yonimdo** [konpa/devicon#29]
https://ceylon-lang.org/

![ceylon](https://cloud.githubusercontent.com/assets/15890521/18586016/1a0638c0-7c23-11e6-9c7d-85c5c6a63fe5.png)

**Comment by oligibson** [comment]
@Yonimdo added in commit - [8be1c20](https://github.com/konpa/devicon/commit/8be1c20e23ca6c996241bdbfb17746a1990505b8) - will be in the next release.
