### ISSUE TITLE
Elm?

### ISSUE THREAD

**Issue by Yonimdo** [konpa/devicon#30]
http://elm-lang.org/

![elm](https://cloud.githubusercontent.com/assets/15890521/18586600/16fcaa80-7c26-11e6-8902-26b49620ee26.png)

**Comment by oligibson** [comment]
@Yonimdo added in commit - [8be1c20](https://github.com/konpa/devicon/commit/8be1c20e23ca6c996241bdbfb17746a1990505b8) - will be in the next release.
