### ISSUE TITLE
Having trouble loading from CDN

### ISSUE THREAD

**Issue by qwertwerty21** [konpa/devicon#31]
Just started having this problem today. Following documentation I linked 
<link rel="stylesheet" href="https://cdn.rawgit.com/konpa/devicon/master/devicon.min.css"> in my html header, but it's been timing out every single time I try to load. Even directly visiting the cdn site results in a connection error.

**Comment by konpa** [comment]
I had some bad nginx config that I fixed today. Is it working fine now? If not, what link do you use?
