### ISSUE TITLE
No Devicon, Icon?

### ISSUE THREAD

**Issue by noobularkid** [konpa/devicon#41]
Why isn't there a DevIcon icon yet? It would be helpful lol.

**Comment by oligibson** [comment]
@konpa do you have the vector versions of the Devicon logo?

**Comment by konpa** [comment]
Yes, it was part of the library at the beginning and I removed it later. You can find it here : https://github.com/konpa/devicon/tree/f935da07a9db2eb1f2f4e8aea63c271b4d5bd7ab/icons/devicon

**Comment by oligibson** [comment]
Thanks @konpa I've added this icon in this [commit](https://github.com/konpa/devicon/commit/eec6e09fc25fb9a0ace6d90ee8e5923a4d409ea3) and I'll now close this issue.
