### ISSUE TITLE
devicon.fr is missing typescript from the available icons

### ISSUE THREAD

**Issue by Jacrys** [konpa/devicon#50]
I spent 30-45 minutes trying to find an svg for TypeScript since devicon.fr didn't show it as available.  I couldn't find one, so I settled on a png and was shoehorning it into the icons directory when I noticed a TS folder and svgs for it.  Could you add them to the site if possible?

**Comment by oligibson** [comment]
@konpa how can we update the website with the latest icons and do a proper release of an up to date npm package?

**Comment by konpa** [comment]
Devicon website is now hosted on Github (gh-pages branch) and up to date.

@oligibson Feel free to update it if needed. If you need help don't hesitate.

Thanks ! :)
