### ISSUE TITLE
Swift icon

### ISSUE THREAD

**Issue by AlexMcArdle** [konpa/devicon#54]
No icon for Swift (or Objective-C).

Wiki Commons has the logo in the public domain:
https://commons.wikimedia.org/wiki/File:Swift_logo.svg

**Comment by AlexMcArdle** [comment]
Also, logo + wordmark
https://commons.wikimedia.org/wiki/File:Swift_logo.svg#/media/File:Swift_logo_with_text.svg

**Comment by Flame2057** [comment]
+1

**Comment by stefanomondino** [comment]
+1

**Comment by oligibson** [comment]
I've added the swift icon in this [commit](https://github.com/konpa/devicon/commit/f5a522a9093ce2813889c4d93e18034649457b6c), it'll be included in the next release.
