### ISSUE TITLE
Typescript Icon not appearing

### ISSUE THREAD

**Issue by akgoode** [konpa/devicon#55]
I used the <i> tag link to insert a typescript icon into my webpage, but it doesn't appear on the screen.  I have successfully loaded about 12 other icons in the exact same format as this one, so I'm confident it is not my error.  I'm going through the files a little bit to see if I can find some inconsistencies, but I'm still unfamiliar with how the whole repo works.

**Comment by konpa** [comment]
What are you calling the tag like ? Are you using the font or the svg version ?

**Comment by konpa** [comment]
If you were talking about the font stylesheet rawgit url from the website, it was not up to date. I generated a new link in the last commit https://github.com/konpa/devicon/commit/9610debb764c3b1ba8739a2eb77f9ec564c61453

**Comment by akgoode** [comment]
Sorry I meant to say that I used the font version inside the I tag to insert it.  When I get back to my computer I will add the new link and test it.
