### ISSUE TITLE
how to change the size of the icon? 

### ISSUE THREAD

**Issue by yaserig** [konpa/devicon#56]
somehow i couldn't change the size of the icon, i'd like to make it bigger, i tried your example with the 2em , but it didn't work. can you give an example of how to manually change its size through css? thank you!

**Comment by nawazishali** [comment]
Have not tried these awesome Icons myself yet but I would love to help you out as I am looking forward to use them in my Portfolio soon. Can you please provide a live example of what you are trying to achieve, May be a Codepen or a JSfiddle and also what Icon you are currently playing with?

**Comment by yaserig** [comment]
hey, Thanks for your fast response! I figured it out, it was the font-size that i should change using em , not the width/height.. which is weird a bit, but as long as it works, that what matters :) , thanks again!

**Comment by nawazishali** [comment]
@yaserig Width/height should only work with the SVG code not with Fonts. Now you are on right track.

**Comment by MiguelBrito1086** [comment]
@yaserig Funny. It's definitely not working for me. I've tried using the font-size and nothing. Just tiny little devicons. 

Any suggestions?

**Comment by crispaulcastaneda** [comment]
You can resize it. e.g "Font-size: 2rem;". It works for me.

**Comment by Stevey144** [comment]
thanks for this bro "Font-size:2rem;"worked perfectly fine for me

**Comment by zim0369** [comment]
I've just installed the devicon plugin for vim. I have no idea of what file to actually edit?

**Comment by amacado** [comment]
@zim0369 I assume you're in the wrong project. This repository/project does not provide a vim plugin. There might be plugins that use this projects icons but you have to ask the question within the project which released the vim plugin :)
