### ISSUE TITLE
Is this project still alive?

### ISSUE THREAD

**Issue by chrisdothtml** [konpa/devicon#57]
There's quite a lot of icon requests coming in regularly, and not much activity in the repo in the past months. Even the PRs haven't had much activity in a while.

**Comment by oligibson** [comment]
@chrisdothtml I'm going to try and review/merge the existing pull requests over the next few days and then put out a release. Then we can move forward and look at the requested icons. 

It would be good to get some contribution of icons, I can help create fonts, review and merge requests if the artwork is done.
