### ISSUE TITLE
Icon request: [NAME] boostrap

### ISSUE THREAD

**Issue by Ramc234** [konpa/devicon#602]
### About the icon
*Short description why you think this icon is matching in our project*
### Links
*Provide helpful links which can be used to take a deeper look into the icon and provide, if available, some resources (svg's) where the icon can be found*
### Preview
*If available, provide some images of the icon you would like to be added*

**Comment by Thomas-Boi** [comment]
Hey @Ramc234 ,

Is the icon supposed to be for Bootstrap? If so, can you please edit the PR title so it's proper please? If it's not Bootstrap, please link the website so people know which technology you are referring to.

**Comment by amacado** [comment]
If it's bootstrap, this issue is invalid since we already added bootstrap `<i class="devicon-bootstrap-plain"></i>`. Anyway: Since the issue/icon request is not properly filled in I decline this issue.
@Ramc234 feel free to reopen/create a new issue following our guidelines :-)
