### ISSUE TITLE
Materialize Icon

### ISSUE THREAD

**Issue by januridp** [konpa/devicon#71]
could you add materialize icon on there?

thanks before

**Comment by Enethion** [comment]
It's already on list #11

**Comment by januridp** [comment]
Oh thank you

**Comment by edwintrumpet** [comment]
I can't find the materialize icon, there's only the material-ui icon.

**Comment by amacado** [comment]
@edwintrumpet feel free to create a new icon request: https://github.com/devicons/devicon/issues/new?assignees=&labels=request%3Aicon&template=icon-request.md&title=Icon+request%3A+%5BNAME%5D 😄
