### ISSUE TITLE
on npm version 2.0 is available instead of 2.2

### ISSUE THREAD

**Issue by sagarkaurav** [konpa/devicon#73]
@oligibson  new version is not published on npm. Please update it.

**Comment by jessamarie** [comment]
@sagarkaurav 

Try `npm install --save devicon-2.2`. It works for me!

**Comment by sagarkaurav** [comment]
@jessamarie  I am using yarn and `yarn add devicon@2.2` doesn't seems to work!.

**Comment by jessamarie** [comment]
@sagarkaurav For some reason you have to add a different package name, but it should work with yarn as well. Use this command instead: `yarn add devicon-2.2`

**Comment by sagarkaurav** [comment]
@jessamarie thanks its worked but i am still curious  why different name is used and why is devicon 2.2 is not available?

**Comment by fpoumian** [comment]
I had the same issue when I tried upgrading from version 2.0 to 2.2 on Yarn (I solved it by removing the original package and installing that separate 2.2 package). Will all future releases be released in separate packages in Yarn?

**Comment by adamski52** [comment]
since 2.2, it's a package named `devicon-2.2` with a version of `2.2.0`.  whoever owns the original `devicon` packages needs to `npm publish` please.

putting the version number in the package name is bad joojoo:  `npm install devicon-2-2@2.2.0` will work.  `npm install devicon@2.2.0` will not.

**Comment by baer** [comment]
To add to @adamski52's comment:
- `devicon-2.2` is a different package published by [boomhq](https://www.npmjs.com/~boomhq)
- That package is NOT owned by @konpa 

@konpa would it be possible to publish the latest to NPM?

**Comment by dougmaitelli** [comment]
Sorry guys, but it looks to me that this repository is not being maintained anymore. Also, if we keep adding icons in a font file it will become too large for projects to use.

I would suggest migrating to: https://github.com/gilbarbara/logos/ and use the SVG files independently.

**Comment by iamclaytonray** [comment]
Hey, we are working on getting back on track. We will be following SEMVER releases from now on! I'll go ahead and close this issue. (Docs will be updated accordingly in the future. Trying to get the website back up at the moment.)
