### ISSUE TITLE
Update Visual Studio Code

### ISSUE THREAD

**Issue by Nikodermus** [konpa/devicon#80]
They recently changed it, so it would be nice to have the latest. Thanks!

![image](https://user-images.githubusercontent.com/7080621/31755747-aa3a92da-b465-11e7-8305-fc295d20d603.png)

**Comment by awakekat** [comment]
Didn't they change the icon to blue? Isn't blue now the latest color? Requesting new blue color. Thanks.

**Comment by Eventyret** [comment]
To add to this, Blue is stable and Green is insider builds.
https://code.visualstudio.com/blogs/2017/10/24/theicon
