### ISSUE TITLE
Icon request

### ISSUE THREAD

**Issue by jesus-novologic** [konpa/devicon#82]
- Phalcon Framework 
- C#
- Object-C
- Markdown

**Comment by knighthawkbro** [comment]
There is already a C# icon (Search csharp). Which Markdown syntax did you want (I.E. Kramdown)?

**Comment by jesus-novologic** [comment]
Markdown Language

https://en.wikipedia.org/wiki/Markdown <https://en.wikipedia.org/wiki/Markdown>

**Comment by konpa** [comment]
#11 updated
