### ISSUE TITLE
Icon request - BizTalk

### ISSUE THREAD

**Issue by estebanpostigo** [konpa/devicon#95]
Hi! Thanks for your already created icons!

Would be great to have BizTalk and SQL ones. Here you could find images and ai/eps for BizTalk that I have found, but I don't know how to create a font icon... Maybe if you give me some kind of guide I could done it myself and contribute it.
The SQL one seems to be exactly the same icon but with a different color. So having one font icon will make available both!

Thanks in advance!

PS. I am attaching one image made by with an idea of how it could be, but maybe it could be improved ;-)

![biztalkserver2016-icon](https://user-images.githubusercontent.com/34768371/34298960-a51ad218-e720-11e7-87d2-2ff7c00d8c75.png)

**Comment by konpa** [comment]
#11 updated
